// ============================================================
// DESIGN TOKENS
// ============================================================
export const C = {
  forestDark:    '#2d3a1e',
  forest:        '#3b4f27',
  forestMid:     '#4a6230',
  forestLight:   '#5c7a3a',
  white:         '#ffffff',
  offWhite:      '#f8f9f6',
  textPrimary:   '#1a1f14',
  textSecondary: '#6b7560',
  textMuted:     '#9aa090',
  border:        '#dde3d8',
  borderFocus:   '#4a6230',
  inputBg:       '#ffffff',
  errorRed:      '#c0392b',
  successGreen:  '#2e7d32',
}

// ============================================================
// SHARED STYLES
// ============================================================
export const S = {
  page: {
    display: 'flex',
    minHeight: '100vh',
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    backgroundColor: C.white,
  },
  leftPanel: {
    flex: '0 0 52%',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  rightPanel: {
    flex: '0 0 48%',
    position: 'relative',
    overflow: 'hidden',
    backgroundImage:
      "url('https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=900&q=80')",
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },
  rightOverlay: {
    position: 'absolute',
    inset: 0,
    background:
      'linear-gradient(135deg, rgba(45,58,30,0.35) 0%, rgba(20,28,12,0.6) 100%)',
  },
  heroCard: {
    position: 'absolute',
    bottom: '80px',
    left: '40px',
    right: '40px',
    background: 'rgba(255,255,255,0.12)',
    backdropFilter: 'blur(18px)',
    WebkitBackdropFilter: 'blur(18px)',
    borderRadius: '20px',
    padding: '32px 36px',
    border: '1px solid rgba(255,255,255,0.22)',
    color: C.white,
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '1.2px',
    color: 'rgba(255,255,255,0.85)',
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.25)',
    borderRadius: '20px',
    padding: '5px 12px',
    marginBottom: '16px',
  },
  heroTitle: {
    fontSize: '34px',
    fontWeight: 800,
    lineHeight: 1.2,
    margin: '0 0 12px 0',
    letterSpacing: '-0.5px',
  },
  heroSubtitle: {
    fontSize: '15px',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.82)',
    margin: 0,
  },
  topBar: {
    padding: '28px 52px',
    borderBottom: `1px solid ${C.border}`,
  },
  brand: {
    fontSize: '15px',
    fontWeight: 700,
    color: C.textPrimary,
    letterSpacing: '-0.2px',
  },
  formWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '48px 52px',
    width: '100%',
    maxWidth: '520px',
    margin: '0 auto',
  },
  heading: {
    fontSize: '32px',
    fontWeight: 800,
    color: C.textPrimary,
    margin: '0 0 8px 0',
    letterSpacing: '-0.6px',
  },
  subheading: {
    fontSize: '14.5px',
    color: C.textSecondary,
    margin: '0 0 40px 0',
    lineHeight: 1.5,
  },
  label: {
    display: 'block',
    fontSize: '13.5px',
    fontWeight: 600,
    color: C.textPrimary,
    marginBottom: '8px',
  },
  inputWrap: {
    position: 'relative',
    marginBottom: '20px',
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '13px 16px',
    fontSize: '14.5px',
    border: `1.5px solid ${C.border}`,
    borderRadius: '10px',
    backgroundColor: C.inputBg,
    color: C.textPrimary,
    outline: 'none',
    transition: 'border-color 0.18s, box-shadow 0.18s',
    fontFamily: 'inherit',
  },
  inputFocused: {
    borderColor: C.forestMid,
    boxShadow: '0 0 0 3px rgba(74,98,48,0.12)',
  },
  inputError: {
    borderColor: C.errorRed,
    boxShadow: '0 0 0 3px rgba(192,57,43,0.10)',
  },
  eyeBtn: {
    position: 'absolute',
    right: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: C.textMuted,
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
  },
  rowBetween: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '28px',
  },
  checkLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13.5px',
    color: C.textSecondary,
    cursor: 'pointer',
    userSelect: 'none',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    accentColor: C.forest,
    cursor: 'pointer',
  },
  linkBtn: {
    fontSize: '13.5px',
    fontWeight: 600,
    color: C.forest,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
    textDecoration: 'none',
  },
  btnPrimary: {
    width: '100%',
    padding: '14px',
    fontSize: '15px',
    fontWeight: 700,
    color: C.white,
    backgroundColor: C.forest,
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'background-color 0.18s',
    fontFamily: 'inherit',
    letterSpacing: '0.1px',
  },
  btnPrimaryHover: {
    backgroundColor: C.forestDark,
  },
  btnDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  backLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '32px',
    fontSize: '13.5px',
    fontWeight: 600,
    color: C.textSecondary,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: 0,
    transition: 'color 0.15s',
  },
  errorMsg: {
    fontSize: '12.5px',
    color: C.errorRed,
    marginTop: '5px',
    marginBottom: '4px',
  },
  successBox: {
    background: 'rgba(74,98,48,0.08)',
    border: '1.5px solid rgba(74,98,48,0.25)',
    borderRadius: '10px',
    padding: '14px 16px',
    fontSize: '13.5px',
    color: C.forest,
    lineHeight: 1.6,
    marginBottom: '24px',
  },
  bottomBar: {
    padding: '20px 52px',
    borderTop: `1px solid ${C.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
  },
  bottomBrand: {
    fontSize: '13px',
    fontWeight: 600,
    color: C.textPrimary,
  },
  bottomLinks: {
    display: 'flex',
    gap: '24px',
  },
  bottomLink: {
    fontSize: '12.5px',
    color: C.textSecondary,
    textDecoration: 'none',
  },
  copyright: {
    fontSize: '12px',
    color: C.textMuted,
  },
  strengthBar: {
    display: 'flex',
    gap: '4px',
    marginTop: '8px',
    marginBottom: '4px',
  },
  strengthLabel: {
    fontSize: '12px',
    marginBottom: '8px',
  },
}